apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform
  description: Platform
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: platform@example.com
    picture: https://avatars.dicebear.com/api/identicon/platform@example.com.svg?background=%23fff&margin=25
  parent: backstage
  children: []
